version: '3.8'

services:
  possum_nginx:
    image: nginx:latest
    container_name: possum_nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs/www:/var/www/certbot
      - ./nginx/certs/letsencrypt:/etc/letsencrypt
      - ./nginx/logs:/var/log/nginx
      - static_volume:/app/static
    networks:
      - possum_network

  possum_certbot:
    image: certbot/certbot:latest
    container_name: possum_certbot
    volumes:
      - ./nginx/certs/www:/var/www/certbot
      - ./nginx/certs/letsencrypt:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - possum_network

  possum:
    build: possum
    image: possum
    container_name: possum
    ports:
      - "8000:8000"
    volumes:
      - ./possum:/opt/services/possum/src
      - static_volume:/app/static
    networks:
      - possum_network

networks:
  possum_network:
    name: possum_network
    driver: bridge

volumes:
  static_volume: